# Generated by Django 3.2.23 on 2023-12-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysqlcrud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=20)),
                ('vname', models.CharField(max_length=100)),
                ('vsal', models.IntegerField()),
            ],
        ),
    ]
